#include<stdlib.h>
#include<complex.h>
#include<ctype.h>
#include<errno.h>
#include<fenv.h>
#include<float.h>
#include<inttypes.h>
#include<iso646.h>
#include<limits.h>
#include<locale.h>
#include<math.h>
#include<stdarg.h>
#include<signal.h>
#include<stdalign.h>
#include<ctype.h>
#include<stdatomic.h>
#include<ctype.h>
#include<ctype.h>
#include<ctype.h>
#include<ctype.h>
#include<ctype.h>
#include<ctype.h>
#include<ctype.h>
